# Generated by Django 4.0.4 on 2022-05-21 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacionGeneral', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenes',
            old_name='estado',
            new_name='estado_orden',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='catidad',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='precio_orden',
        ),
        migrations.AddField(
            model_name='ordenes',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='precio_serv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='precio_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacionGeneral.servicio'),
        ),
    ]
