# Generated by Django 4.0.4 on 2022-05-21 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionGeneral', '0002_rename_estado_ordenes_estado_orden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenes',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='precio_serv',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='servicio',
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='estado_orden',
            field=models.CharField(choices=[('New', 'Nuevo'), ('Accepted', 'Aceptado'), ('Ongoing', 'En curso'), ('Completed', 'Finalizado'), ('Cancelled', 'Cancelado')], default='New', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Ordenes_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('precio_serv', models.IntegerField(default=0)),
                ('orden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacionGeneral.ordenes')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacionGeneral.servicio')),
            ],
        ),
    ]
